# frozen_string_literal: true



require_relative 'composition_mandatory_sections/suite_100ballot_generate_bundle_using_ips_summary_validation_composition_mandatory_sections_sections_shall_be_correctly_populated_if_a_value_is_known'

require_relative 'composition_mandatory_sections/suite_100ballot_generate_bundle_using_ips_summary_validation_composition_mandatory_sections_sections_shall_be_capable_of_populating_sectionentry_with_the_referenced_profiles_and_should_correctly_populate_sectionentry_if_a_value_is_known'


module AUPSTestKit
  # Automatically generated primitive group for Composition Mandatory Sections
  class AUPSSuite100ballotGenerateBundleUsingIpsSummaryValidationCompositionMandatorySections < Inferno::TestGroup
    title 'Composition Mandatory Sections'
    description 'Displays information about Composition Mandatory Sections in the Composition resource.'
    id :suite_100ballot_generate_bundle_using_ips_summary_validation_composition_mandatory_sections

    
    test from: :suite_100ballot_generate_bundle_using_ips_summary_validation_composition_mandatory_sections_sections_shall_be_correctly_populated_if_a_value_is_known
    
    test from: :suite_100ballot_generate_bundle_using_ips_summary_validation_composition_mandatory_sections_sections_shall_be_capable_of_populating_sectionentry_with_the_referenced_profiles_and_should_correctly_populate_sectionentry_if_a_value_is_known
    
  end
end
