AllCops:
  NewCops: enable
  Exclude:
    - "lib/au_ps_inferno/1.0.0-ballot/**/*"
    - "spec/integration/suite_100ballot_snapshots_spec.rb"

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/MethodName:
  Exclude:
    - "lib/au_ps_inferno/generator/generator.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/unit/basic_test/composition_section_check_resources_ms_elements_module_spec.rb"
    - "spec/unit/basic_test/composition_section_read_module_spec.rb"
    - "spec/unit/example_spec.rb"
    - "spec/unit/example_spec_muted.rb"
    - "spec/integration/suite_100ballot_snapshots_spec_muted.rb"

Lint/EmptyBlock:
  Exclude:
    - "spec/fixtures/example_suite.rb"

Layout/LineLength:
  Exclude:
    - "spec/unit/basic_test/composition_section_check_resources_ms_elements_module_spec.rb"
    - "spec/unit/basic_test/composition_section_read_module_spec.rb"
    - "spec/integration/suite_100ballot_snapshots_spec_muted.rb"

Metrics/MethodLength:
  Exclude:
    - "spec/integration/suite_100ballot_snapshots_spec_muted.rb"
    - "spec/unit/basic_test/composition_section_check_resources_ms_elements_module_spec.rb"
    - "lib/au_ps_inferno/utils/basic_test/composition_section_check_resources_ms_elements_module.rb"

Metrics/AbcSize:
  Exclude:
    - "spec/integration/suite_100ballot_snapshots_spec_muted.rb"
