AllCops:
  NewCops: enable
  Exclude:
    - "spec/spec_helper.rb"
    - "lib/au_ps_inferno/0.5.0-preview/**/*"
    - "lib/au_ps_inferno/1.0.0-ballot/**/*"
    - "aidbox_config.rb"
    - "lib/au_ps_inferno/utils/basic_test_class.rb"
    - "lib/au_ps_inferno/generator/suite_structure.rb"
Gemspec/DevelopmentDependencies:
  Enabled: false
