AllCops:
  NewCops: enable
  Exclude:
    - "lib/au_ps_inferno/1.0.0-ballot/**/*"
    - "spec/integration/suite_100ballot_snapshots_spec.rb"

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/MethodName:
  Exclude:
    - "lib/au_ps_inferno/generator/generator.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/unit/basic_test/composition_section_check_resources_ms_elements_module_spec.rb"

Layout/LineLength:
  Exclude:
    - "spec/unit/basic_test/composition_section_check_resources_ms_elements_module_spec.rb"
