services:
  inferno:
    depends_on:
      validator-api-worker:
        condition: service_started
  inferno-worker:
    depends_on:
      validator-api-worker:
        condition: service_started
  validator-api-worker:
    image: ghcr.io/beda-software/aidbox-validator/aidbox-validator:main-891628f
    depends_on:
      validator-api:
        condition: service_healthy
    links:
      - validator-api
    env_file:
      - ./env/app
      - .env
    tty: true
  validator-api:
    image: healthsamurai/aidboxone:2512.2
    environment: !override {}
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres:database"
    ports:
      - "127.0.0.1:3500:3500"
    env_file:
      - ./env/aidbox
      - .env
    volumes: !override
      - ./resources:/resources
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      interval: 1s
      timeout: 20s
      retries: 100
      test: curl --fail http://validator-api:3500/health || exit 1
  aidbox-configure:
    build:
      context: ./
    volumes:
      - ./:/opt/inferno/
    working_dir: /opt/inferno
    command: ruby aidbox_config.rb
    depends_on:
      validator-api:
        condition: service_healthy
    env_file:
      - ./env/aidbox
