version: '3'
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
      - ./lib/:/opt/inferno/lib
      - ./:/opt/inferno/
    depends_on:
      validator-api-worker:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
      POSTGRES_USER: postgres
      TX_SERVER_URL: https://tx.dev.hl7.org.au/fhir
  inferno-worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      validator-api-worker:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
      POSTGRES_USER: postgres
  validator-api-worker:
    image: ghcr.io/beda-software/aidbox-validator/aidbox-validator:main-a467395
    depends_on:
      validator-api:
        condition: service_healthy
    links:
      - validator-api
    env_file:
      - ./env/app
      - .env
    tty: true
  validator-api:
    image: healthsamurai/aidboxone:2510
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - 'postgres:database'
    ports:
      - '127.0.0.1:3500:3500'
    env_file:
      - ./env/aidbox
      - .env
    volumes:
      - ./resources:/resources
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      interval: 1s
      timeout: 20s
      retries: 100
      test: curl --fail http://validator-api:3500/health || exit 1
  nginx:
    image: nginx
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      validator-api:
        condition: service_started
      inferno:
        condition: service_started
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
