# frozen_string_literal: true



require_relative 'au_ps_composition_must_support_conformance/suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_mandatory_must_support_element_shall_be_able_to_be_populated_if_a_value_is_known_and_allowed_to_share'

require_relative 'au_ps_composition_must_support_conformance/suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_optional_must_support_elements_shall_be_correctly_populated_if_a_value_is_known'

require_relative 'au_ps_composition_must_support_conformance/suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_must_support_subelements_of_a_complex_element_shall_be_correctly_populated_if_a_value_is_known'

require_relative 'au_ps_composition_must_support_conformance/suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_optional_must_support_slices_shall_be_populated_if_a_value_is_known'


module AUPSTestKit
  # Automatically generated primitive group for AU PS Composition Must Support Conformance
  class AUPSSuite100ballotRetrieveAuPsBundleValidationTestsAuPsCompositionMustSupportConformance < Inferno::TestGroup
    title 'AU PS Composition Must Support Conformance'
    description 'Verifies that Composition Must Support elements (mandatory, optional, sub-elements, slices) are correctly populated when data is known.'
    id :suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance
    
    
    run_as_group
    

    
    test from: :suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_mandatory_must_support_element_shall_be_able_to_be_populated_if_a_value_is_known_and_allowed_to_share
    
    test from: :suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_optional_must_support_elements_shall_be_correctly_populated_if_a_value_is_known
    
    test from: :suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_must_support_subelements_of_a_complex_element_shall_be_correctly_populated_if_a_value_is_known
    
    test from: :suite_100ballot_retrieve_au_ps_bundle_validation_tests_au_ps_composition_must_support_conformance_optional_must_support_slices_shall_be_populated_if_a_value_is_known
    
  end
end
