# frozen_string_literal: true

module AUPSTestKit
  # Test data for SingleFileSuiteBuilder: which groups/tests to generate and their
  # titles/descriptions, kept separate from the builder's DSL-wiring logic.
  module SingleFileSuiteConfig
    BUNDLE_SOURCES = [
      {
        top_id: :au_ps_bundle_instance,
        top_title: 'AU PS Bundle Instance',
        top_description: 'Validates a static AU PS bundle instance for profile conformance, Must Support ' \
                         'elements, and composition sections.',
        acquisition_from: :provided_bundle_test_class,
        acquisition_group_title: 'Provide AU PS Bundle',
        acquisition_group_description: 'Loads the Bundle resource pasted as text and stores it for the ' \
                                       'validation tests in this group.',
        acquisition_test_title: 'Bundle instance is parsable',
        acquisition_test_description: 'The provided text can be parsed as a FHIR resource (JSON or XML) and ' \
                                      'its resourceType is Bundle. The parsed Bundle is stored for the ' \
                                      'validation tests in this group; conformance to the AU PS Bundle profile ' \
                                      'is tested separately under Bundle Validation.',
        bundle_valid_title: 'Bundle is valid against AU PS Bundle',
        bundle_valid_description: 'The Bundle resource is valid against the AU PS Bundle profile using FHIR validator',
        bundle_valid_ips_title: 'Bundle is valid against IPS Bundle',
        bundle_valid_ips_description: 'The Bundle resource is valid against the IPS Bundle profile using FHIR validator'
      },
      {
        top_id: :retrieve_au_ps_bundle_validation_tests,
        top_title: 'Retrieve AU PS Bundle validation tests',
        top_description: 'Retrieve document Bundle using Bundle read interaction or other HTTP GET request ' \
                         'and verify response is valid AU PS Bundle',
        acquisition_from: :retrieve_bundle_test_class,
        acquisition_group_title: 'Retrieve AU PS Bundle',
        acquisition_group_description: 'Retrieves the document Bundle using a Bundle read interaction or a ' \
                                       'direct HTTP GET request and stores it for the validation tests in this group.',
        acquisition_test_title: 'Bundle is retrievable from the FHIR server',
        acquisition_test_description: 'A Bundle can be retrieved via a Bundle read interaction (FHIR server ' \
                                      'URL and Bundle ID) or a direct HTTP GET of the Bundle URL, returning ' \
                                      'HTTP 200 with a parsable FHIR Bundle. The retrieved Bundle is stored ' \
                                      'for the validation tests in this group.',
        bundle_valid_title: 'Retrieved Bundle is valid against AU PS Bundle profile',
        bundle_valid_description: 'Verifies that the bundle retrieved from the server conforms to the AU PS Bundle profile.',
        bundle_valid_ips_title: 'Retrieved Bundle is valid against IPS Bundle profile',
        bundle_valid_ips_description: 'Verifies that the bundle retrieved from the server conforms to the IPS Bundle profile.'
      },
      {
        top_id: :generate_au_ps_using_ips_summary_validation_tests,
        top_title: 'Generate AU PS using IPS $summary validation tests',
        top_description: 'Generate AU Patient Summary using IPS $summary operation and verify response is ' \
                         'valid AU PS Bundle',
        acquisition_from: :generate_summary_bundle_test_class,
        acquisition_group_title: 'Generate AU PS Bundle using $summary',
        acquisition_group_description: 'Invokes the IPS $summary operation on the FHIR server and stores the ' \
                                       'returned Bundle for the validation tests in this group.',
        acquisition_test_title: 'Patient summary Bundle is generated by the IPS $summary operation',
        acquisition_test_description: 'The IPS $summary operation returns HTTP 200 with a Bundle. The ' \
                                      'generated Bundle is stored for the validation tests in this group.',
        bundle_valid_title: 'Generated Bundle is valid against AU PS Bundle profile',
        bundle_valid_description: 'Verifies that a bundle produced by the IPS $summary operation conforms to the AU PS Bundle profile.',
        bundle_valid_ips_title: 'Generated Bundle is valid against IPS Bundle profile',
        bundle_valid_ips_description: 'Verifies that a bundle produced by the IPS $summary operation conforms to the IPS Bundle profile.'
      }
    ].freeze

    ACTOR_GROUPS = [
      {
        key: 'subject',
        group_id: :au_ps_composition_subject,
        group_title: 'AU PS Composition Subject',
        group_description: 'Verify the referenced subject is a correctly populated AU PS Patient resource.',
        group_optional: false,
        resource_type_id: :subject_resource_type_is_valid,
        resource_type_text: 'Subject reference in the AU PS Composition SHALL resolve to a valid resource ' \
                            'type (Patient).',
        ms_elements_id: :subject_ms_elements,
        ms_elements_text: 'Must Support elements SHALL be populated if a value is known',
        ms_subelements_id: :subject_ms_subelements_populated,
        ms_subelements_text: 'Must Support sub-element SHALL be populated if a value is known and the parent is populated',
        ms_identifier_slices_id: :subject_ms_identifier_slices,
        ms_identifier_slices_title: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_description: 'Must Support identifier slices SHALL be populated if a value is ' \
                                          'known (i.e. ihi, dva, medicare).',
        ms_identifier_slices_method: :test_subject_ms_identifier_slices
      },
      {
        key: 'author',
        group_id: :au_ps_composition_author,
        group_title: 'AU PS Composition Author',
        group_description: 'Verify the referenced author is a correctly populated AU PS Practitioner, AU PS ' \
                           'PractitionerRole, AU PS Patient, AU PS RelatedPerson, AU PS Organization profiles ' \
                           'or Device resource.',
        group_optional: false,
        resource_type_id: :author_resource_type_is_valid,
        resource_type_text: 'Author reference in the AU PS Composition SHALL resolve to a valid resource type ' \
                            '(Practitioner, PractitionerRole, Device, Patient, RelatedPerson, Organization).',
        ms_elements_id: :author_ms_elements,
        ms_elements_text: 'Must Support elements SHALL be populated if a value is known',
        ms_subelements_id: :author_ms_subelements,
        ms_subelements_text: 'Must Support sub-elements SHALL be populated if a value is known',
        ms_identifier_slices_id: :author_ms_identifier_slices,
        ms_identifier_slices_title: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_description: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_method: :test_composition_author_ms_identifier_slices
      },
      {
        key: 'custodian',
        group_id: :au_ps_composition_custodian,
        group_title: 'AU PS Composition Custodian',
        group_description: 'Verify the referenced custodian is a correctly populated AU PS Organization resource.',
        group_optional: true,
        resource_type_id: nil,
        resource_type_text: nil,
        ms_elements_id: :custodian_ms_elements,
        ms_elements_text: 'Must Support element SHALL be populated if a value is known',
        ms_subelements_id: :custodian_ms_subelements,
        ms_subelements_text: 'Must Support sub-element SHALL be populated if a value is known',
        ms_identifier_slices_id: :custodian_ms_identifier_slices,
        ms_identifier_slices_title: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_description: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_method: :test_composition_custodian_ms_identifier_slices
      },
      {
        key: 'attester',
        group_id: :au_ps_composition_attester,
        group_title: 'AU PS Composition Attester',
        group_description: 'Verify the referenced attester.party is a correctly populated AU PS Patient, ' \
                           'RelatedPerson, Practitioner, PractitionerRole, or Organization resource.',
        group_optional: true,
        resource_type_id: nil,
        resource_type_text: nil,
        ms_elements_id: :attester_party_ms_elements,
        ms_elements_text: 'Must Support elements SHALL be populated if a value is known',
        ms_subelements_id: :attester_party_ms_subelements,
        ms_subelements_text: 'Must Support sub-element SHALL be populated if a value is known',
        ms_identifier_slices_id: :attester_party_ms_identifier_slices,
        ms_identifier_slices_title: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_description: 'Must Support identifier slices SHALL be populated if a value is known',
        ms_identifier_slices_method: :test_composition_attester_party_ms_identifier_slices
      }
    ].freeze

    DEFAULT_SECTION_TIERS = [
      {
        group_id: :au_ps_composition_mandatory_sections,
        group_title: 'AU PS Composition Mandatory Sections',
        group_description: 'Verify the mandatory sections are correctly populated in the AU PS Composition resource',
        codes: %w[11450-4 48765-2 10160-0],
        mandatory: true,
        populated_optional: false,
        populated_id: :sections_shall_populated,
        populated_title: 'AU PS Composition Mandatory Sections are correctly populated',
        populated_description: 'Mandatory section SHALL be correctly populated if a value is known',
        entry_profiles_id: :mandatory_sections_entry_profiles,
        entry_profiles_title: 'AU PS Composition Mandatory Sections capable of populating referenced profiles',
        entry_profiles_description: 'Mandatory section SHALL be capable of populating section.entry with the ' \
                                    'referenced profiles and SHOULD correctly populate section.entry if a value is known.',
        entry_profiles_dsl_optional: false,
        nilknown_warning_id: :mandatory_sections_nilknown_warning,
        nilknown_warning_title: 'AU PS Composition Mandatory Sections do not rely on emptyReason=nilknown',
        nilknown_warning_description: 'Warns when a mandatory section (Problems, Allergies, Medications) uses ' \
                                      'Composition.section.emptyReason = nilknown instead of an explicit ' \
                                      "negation code on the section's entry resource (e.g. " \
                                      'AllergyIntolerance.code = 716186003 |No known allergy|). AU PS prefers ' \
                                      'the explicit-entry pattern used by FHIR, IPS and AU Core over ' \
                                      'emptyReason - this is a warning, not a failure.'
      },
      {
        group_id: :au_ps_composition_recommended_sections,
        group_title: 'AU PS Composition Recommended Sections',
        group_description: 'Verify the recommended sections are correctly populated in the Composition resource',
        codes: %w[11369-6 30954-2 47519-4 46264-8],
        mandatory: false,
        populated_optional: true,
        populated_id: :sections_should_populated,
        populated_title: 'AU PS Composition recommended sections are correctly populated',
        populated_description: 'Recommended sections SHOULD be correctly populated if a value is known',
        entry_profiles_id: :recommended_sections_entry_profiles,
        entry_profiles_title: 'AU PS Composition Recommended Sections capable of populating referenced profiles',
        entry_profiles_description: 'Recommended section SHALL be capable of populating section.entry with the ' \
                                    'referenced profiles and SHOULD correctly populate section.entry if a value is known.',
        entry_profiles_dsl_optional: false
      },
      {
        group_id: :au_ps_composition_optional_sections,
        group_title: 'AU PS Composition Optional Sections',
        group_description: 'Verify the optional sections are correctly populated in the AU PS Composition resource',
        codes: %w[42348-3 104605-1 47420-5 11348-0 10162-6 81338-6 18776-5 29762-2 8716-3],
        mandatory: false,
        populated_optional: true,
        populated_id: :sections_may_populated,
        populated_title: 'AU PS Composition optional sections are correctly populated',
        populated_description: 'Optional section MAY be correctly populated if a value is known',
        entry_profiles_id: :optional_sections_entry_profiles,
        entry_profiles_title: 'AU PS Composition Optional Sections capable of populating referenced profiles',
        entry_profiles_description: 'Optional section SHALL be capable of populating section.entry with the ' \
                                    'referenced profiles and SHOULD correctly populate section.entry if a value is known.',
        entry_profiles_dsl_optional: true
      }
    ].freeze
  end
end
